/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Calculator */

#ifndef _Included_com_example_Calculator
#define _Included_com_example_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Calculator
 * Method:    multiply
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray  JNICALL Java_com_example_Calculator_multiply
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
